---
# General defaults
ami_create: True
disable_rhui: True

# Versions - these are the defaults, see individual profile variables if they need to be different
# Tower version (last successful version was 3.2.5)
tower_version: "3.2.5"
ocp_version: "3.10"
# Docker version
docker_version: "1.13.1"

# Ansible variable for version cannot use 'ansible_version' as this conflicts with one of Ansible's core variables
ansible_rpm_version: "2.5"

# EPEL
epel_setup: False
epel_latest_package: "http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"

# All Repositories
all_repos:
  - rhel-7-server-rpms
  - rhel-7-server-optional-rpms
  - rhel-7-server-extras-rpms
  - rhel-7-server-rh-common-rpms

# All yum packages
yum_update: True
all_yum_packages:
  - wget
  - git
  - net-tools
  - bind-utils
  - bash-completion
  - vim

# All pip packages Note that this will require the package 'python2-pip'
all_pip_packages: []
...
