---
- name: Include ami_build_type role
  hosts: instance
  #strategy: debug
  become: true
  gather_facts: yes
  vars:
    - ansible_user: ec2-user
  vars_files:
    - aws_vars.yml
  roles:
    - { role: ami-builder, when: ami_build_type is defined }
...
