---
# Load vars for requested profile, which are needed in the following tasks
- import_tasks: profiles/vars.yml

# Every AMI will get the same subscription tasks
- import_tasks: rh_subscription.yml

# This is a generic install which is driven by the profile vars
- import_tasks: install.yml
  become: True

# Call profle specific tasks
- import_tasks: profiles/tasks.yml

# Call create_ami if requested
- import_tasks: create_ami.yml
  when: ami_create | default(True) | bool == True
...
