---
- name: Register to Red Hat CDN
  redhat_subscription:
    state: present
    username: "{{ rhn_username }}"
    password: "{{ rhn_password }}"
    pool_ids: "{{ rhn_pool_ids }}"
  become: true

- name: Disable RHUI and only use the Red Hat CDN for content
  command: yum -y erase "{{ item }}"
  with_items:
    - rh-amazon-rhui-client
  args:
    warn: no
  become: true

- name: Disable all repos on the system
  command: subscription-manager repos --disable="*"
  become: true
...
