---
yum_update: False
epel_setup: False
ami_create: True
disable_rhui: True

yum_repos:
  - rhel-7-server-ose-{{ ocp_version }}-rpms
  - rhel-7-fast-datapath-rpms
  - rhel-7-server-ansible-{{ ansible_rpm_version }}-rpms

# yum packages
## NOTE: For version previous to 3.10, you must also include - atomic-openshift-utils
yum_packages:
  - iptables-services
  - bridge-utils
  - kexec-tools
  - sos
  - psacct
  - atomic
  - docker-{{ docker_version }}
  - openshift-ansible

# pip packages
pip_packages: []
...
