---
- name: Add Tower Cloud Credential
  command: >
    tower-cli credential create
    --name="{{ tower_credential_cloud }}"
    --inputs='{"username": "{{ tower_credential_cloud_username }}", "password": "{{ tower_credential_cloud_password }}"}'
    --credential-type="{{ tower_credential_cloud_type }}"
    --organization="{{ tower_org }}"
    {{ tower_cli_options }}
...
