---
- name: Stage {{ tower_credential_machine }} Private Key
  synchronize:
    src: "{{ tower_credential_machine_ssh_key_data_file }}"
    dest: "/tmp/{{ tower_credential_machine_ssh_key_data_file }}"

- name: Copy template for {{ tower_credential_machine }} input
  template:
    src: tower_credential_machine_input.j2
    dest: /tmp/tower_credential_machine_input

- name: Massage private key
  shell: awk '{printf "  %s\n", $0}' < /tmp/{{ tower_credential_machine_ssh_key_data_file }} >> /tmp/tower_credential_machine_input

- name: Add Tower Machine Credential
  command: >
    tower-cli credential create
    --name="{{ tower_credential_machine }}"
    --inputs=@/tmp/tower_credential_machine_input
    --credential-type="{{ tower_credential_machine_type }}"
    --organization="{{ tower_org }}"
    {{ tower_cli_options }}

- name: Remove {{ tower_credential_machine }} staging files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /tmp/tower_credential_machine_input
    - /tmp/{{ tower_credential_machine_ssh_key_data_file }}
...
