---
- name: Include the variables
  include_vars: 
    file: ../defaults/main.yml

- name: Stage {{ tower_credential_machine }} Private Key
  synchronize:
    src: "{{ tower_credential_machine_ssh_key_data }}"
    dest: "/tmp/"


- debug:
  var: tower_credential_machine_kind
  verbosity: 2

- name: Add Tower Machine Credential
  tower_credential:
    #name: "{{ tower_credential_machine }}"
    name: "RHTE SSH"
    # description: "{{ tower_credential_machine_description }}"
    description: "Private SSH Key"
    #kind: "{{ tower_credential_machine_kind }}"
    kind: "ssh"
    # organization: "{{ tower_org }}"
    organization: "Default"
    state: present
    #ssh_key_data: "/tmp{{ tower_credential_machine_ssh_key_data }}"
    ssh_key_data: "/tmp/summit-2018-L1066-Managing-OCP.pem"
    #username: "{{ tower_credential_machine_username }}"
    username: "ec2-user"
    #tower_host: "{{ tower_host }}"
    tower_host: "localhost"
    tower_username: "{{ tower_username }}"
    tower_password: "{{ tower_password }}"

- name: Remove {{ tower_credential_machine }} staging file
  file:
    path: "/tmp/{{ tower_credential_machine_ssh_key_data }}"
    state: absent
...
