---
- name: Include the credentials playbook which adds the ssh key and aws creds to Tower.
  import_tasks: credentials.yml

- name: Create an AMI from the configured VM
  local_action:
    module: ec2_ami
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
    instance_id: "{{ instance_id }}"
    name: "{{ ami_tower }}"
    region: "{{ aws_region }}"
    wait: yes
  register: ami_id

- debug:
    var: ami_id.image_id
    verbosity: 1
...
