---
# General defaults
ami_create: True

# EPEL
epel_setup: False
epel_latest_package: "http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"

# All Repositories
all_repos:
  - rhel-7-server-rpms
  - rhel-7-server-optional-rpms
  - rhel-7-server-extras-rpms

# All yum packages
yum_update: True
all_yum_packages:
  - wget
  - git
  - net-tools
  - bind-utils
  - bash-completion

# All pip packages Note that this will require the package 'python2-pip'
all_pip_packages: []
...
