---
# All Repositories
all_repos:
  - rhel-7-server-rpms
  - rhel-7-server-optional-rpms
  - rhel-7-server-extras-rpms

ansible_host_repos:
  - rhel-7-server-ansible-2-rpms

# Tower general config
tower_host: localhost
tower_username: admin
tower_password: "{{ tower_password }}"
tower_cli_verbosity: "--verbose"
tower_org: "Default"

# Tower version (last successful version was 3.2.3)
tower_version: 3.2.3

# Tower setup archive
tower_setup_archive: https://releases.ansible.com/ansible-tower/setup/ansible-tower-setup-{{ tower_version }}.tar.gz

# All yum packages
all_yum_packages:
  - wget
  - git
  - net-tools
  - bind-utils
  - bash-completion

ansible_host_yum_packages:
  - ansible
  - python-boto3
  - python-boto
  - tmux
  - screen

# Tower yum packages
tower_yum_packages:
  - wget
  - git
  - net-tools
  - bind-utils
  - bash-completion
  - iptables-services
  - sos
  - psacct
  - python2-ansible-tower-cli
  - ansible
  - python-boto3
  - python-boto
  - python2-pip
  - pyOpenSSL
  - python-netaddr
  - python-six
  - python-click
  - python-httplib2
  - python2-pip

# Tower pip packages
tower_pip_packages:
  - pexpect

# Local directory to clone git repos into
repo_dir: ~/repos

# Git repos to clone
repos:
  - https://github.com/scollier/ansible-ami-builder.git
  - https://github.com/sabre1041/managing-ocp-install-beyond.git

# Tower machine credential
tower_credential_machine: "SSH"
tower_credential_machine_config: true
tower_credential_machine_description: "Private SSH Key"
tower_credential_machine_type: "Machine"
tower_credential_machine_ssh_key_data_file: "{{ tower_credential_machine_ssh_key_data_file }}"
tower_credential_machine_username: "ec2-user"

# Tower cloud credential
tower_credential_cloud: "AWS"
tower_credential_cloud_config: true
tower_credential_cloud_description: "AWS Access and Secret"
tower_credential_cloud_type: "Amazon Web Services"
tower_credential_cloud_username: "{{ tower_ec2_access_key }}"
tower_credential_cloud_password: "{{ tower_ec2_secret_key }}"

# Tower demo objects
tower_credential_machine_demo: "Demo Credential"
tower_inventory_demo: "Demo Inventory"
tower_job_template_demo: "Demo Job Template"
tower_project_demo: "Demo Project"
...
