---
# Tower general config
tower_host: localhost
tower_username: admin
tower_password: "{{ tower_password }}"

# Tower version (last successful version was 3.2.3)
tower_version: 3.2.3

# Tower setup archive
tower_setup_archive: https://releases.ansible.com/ansible-tower/setup/ansible-tower-setup-{{ tower_version }}.tar.gz

# Tower yum packages
tower_yum_packages:
  - wget
  - git
  - net-tools
  - bind-utils
  - bash-completion
  - iptables-services
  - sos
  - psacct
  - python2-ansible-tower-cli
  - ansible
  - python-boto3
  - python-boto
  - python2-pip

# Tower pip packages
tower_pip_packages:
  - pexpect
...
