---
- import_tasks: ocp.yml
  when: ami_build_type == "ocp"

- import_tasks: http.yml
  when: ami_build_type == "http"

- import_tasks: tower/tower.yml
  when: ami_build_type == "tower"

- import_tasks: rh-container-lab.yml
  when: ami_build_type == "rh-container-lab"

- import_tasks: ansible_host.yml
  become: yes
  become_user: "{{ ansible_user }}"
  when: ami_build_type == "ansible_host"
...
