---
- name: Add the Docker group
  group:
    name: docker
    state: present
  become: true

- name: Add ec2-user to the Docker group
  user:
    name: ec2-user
    groups: docker
  become: true

- name: Restart Docker
  service:
    name: docker-latest
    state: restarted
  become: true

- name: Start firewalld
  service:
    name: firewalld
    state: restarted
  become: true

- name: Create the firewalld dockerc zone
  command: firewall-cmd --permanent --new-zone dockerc

- name: Reload the firewalld dockerc zone
  command: firewall-cmd --reload

- name: configure firewalld dockerc zone
  firewalld:
    zone: dockerc
    source: 172.17.0.0/16
    permanent: true
    state: enabled
  become: true

- name: Add tcp ports to dockerc zone
  firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
  with_items:
    - 8443/tcp
  become: true

- name: Add udp ports to dockerc zone
  firewalld:
    zone: dockerc
    port: "{{ item }}"
    permanent: true
    state: enabled
  with_items:
    - 53/udp
    - 8053/udp
  become: true

- name: Add tcp ports to public zone
  firewalld:
    zone: public
    port: "{{ item }}"
    permanent: true
    state: enabled
  with_items:
    - 8443/tcp
    - 80/tcp
    - 53/tcp
    - 443/tcp
    - 2379/tcp
    - 2380/tcp
    - 8053/tcp
    - 8443/tcp
    - 8444/tcp
    - 10250/tcp
  become: true

- name: Add udp ports to public zone
  firewalld:
    zone: public
    state: enabled
    permanent: true
    port: "{{ item }}"
  with_items:
    - 53/udp
    - 4789/udp
    - 8053/udp
  become: true

- name: Reload firewalld
  systemd:
    name: firewalld
    state: reloaded
  become: true

- name: Configure sysctl
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present
    reload: yes
  become: true

- name: Create a directory to clone everything into
  file:
    path: /home/ec2-user/rh-container-lab
    state: directory

- name: Clone the git repo
  git:
    repo: 'https://github.com/dustymabe/summit-2018-container-lab'
    dest: /home/ec2-user/summit-2018-container-lab

- name: Move the OC startup scripts to the home directory
  copy:
    src: "{{ item }}"
    dest: /home/ec2-user/
    owner: ec2-user
    group: ec2-user
    mode: 0755
    remote_src: yes
  with_items:
    - /home/ec2-user/summit-2018-container-lab/scripts/host/start-oc.sh
    - /home/ec2-user/summit-2018-container-lab/scripts/host/cleanup-oc.sh
  become: true

- name: Cleanup repo dir
  file:
    path: /home/ec2-user/summit-2018-container-lab
    state: absent

- name: copy over the registries file
  copy:
    src: registries.conf
    dest: /etc/containers/registries.conf
  become: true

- name: Restart Docker
  service:
    name: docker-latest
    state: restarted
    enabled: yes
  become: true

- name: Run the script and cache the images
  shell: /home/ec2-user/start-oc.sh
  async: 600
  poll: 0
  register: start_oc

- name: Grab podman and builda repos
  get_url:
    url: "{{ repo_crio }}"
    dest: /etc/yum.repos.d/builda.repo
...
