---
- name: Load profile variables for 'ocp'
  include_vars: ../vars/ocp.yml
  when: ami_config == "ocp"

- name: Load profile variables for 'http'
  include_vars: ../vars/http.yml
  when: ami_config == "http"

- include_vars: ../vars/tower.yml
  when: ami_config == "tower"

- name: Load profile variables for 'rh-container-lab'
  include_vars: ../vars/rh-container-lab.yml
  when: ami_config == "rh-container-lab"

- name: Load profile variables for 'ansible_host'
  include_vars: ../vars/ansible_host.yml
  when: ami_config == "ansible_host"
...
